services:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: always
    environment:
      - ./.env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
    ports:
      - "443:443"
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
  wordpress: