services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./web:/var/www/html
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    restart: always
    volumes:
      - ./web:/var/www/html
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: always